name: flutter_movie_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  common:
    path: common
  data:
    path: data
  domain:
    path: domain
  presentation:
    path: presentation
  cupertino_icons: ^1.0.2
  injectable: ^2.1.1
  get_it: ^7.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  mockito: ^5.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
