// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpgR6yyJod0znwkyFxfR8IFmJZegL4SuU',
    appId: '1:462905067998:web:e248347670177132fe754f',
    messagingSenderId: '462905067998',
    projectId: 'fluttermovieapp-dbf6c',
    authDomain: 'fluttermovieapp-dbf6c.firebaseapp.com',
    storageBucket: 'fluttermovieapp-dbf6c.appspot.com',
    measurementId: 'G-1PZC6VSERY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOvr1waRl_c69esl-Od3JzWZnI_kWcKAw',
    appId: '1:462905067998:android:f12129f8f7467800fe754f',
    messagingSenderId: '462905067998',
    projectId: 'fluttermovieapp-dbf6c',
    storageBucket: 'fluttermovieapp-dbf6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGS4E7e4vR8VPBP8a9GpnTR6zoWH5IrAQ',
    appId: '1:462905067998:ios:5d8490acc3b3ee30fe754f',
    messagingSenderId: '462905067998',
    projectId: 'fluttermovieapp-dbf6c',
    storageBucket: 'fluttermovieapp-dbf6c.appspot.com',
    iosBundleId: 'com.argahutama.flutterMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGS4E7e4vR8VPBP8a9GpnTR6zoWH5IrAQ',
    appId: '1:462905067998:ios:8c75b0c2957156abfe754f',
    messagingSenderId: '462905067998',
    projectId: 'fluttermovieapp-dbf6c',
    storageBucket: 'fluttermovieapp-dbf6c.appspot.com',
    iosBundleId: 'com.argahutama.flutterMovieApp.RunnerTests',
  );
}
